/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartupMvpRouteImport } from './routes/startup-mvp'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuyTrinhRouteImport } from './routes/quy-trinh'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as HoTroSinhVienRouteImport } from './routes/ho-tro-sinh-vien'
import { Route as DuAnRouteImport } from './routes/du-an'
import { Route as DichVuRouteImport } from './routes/dich-vu'
import { Route as IndexRouteImport } from './routes/index'

const StartupMvpRoute = StartupMvpRouteImport.update({
  id: '/startup-mvp',
  path: '/startup-mvp',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuyTrinhRoute = QuyTrinhRouteImport.update({
  id: '/quy-trinh',
  path: '/quy-trinh',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const HoTroSinhVienRoute = HoTroSinhVienRouteImport.update({
  id: '/ho-tro-sinh-vien',
  path: '/ho-tro-sinh-vien',
  getParentRoute: () => rootRouteImport,
} as any)
const DuAnRoute = DuAnRouteImport.update({
  id: '/du-an',
  path: '/du-an',
  getParentRoute: () => rootRouteImport,
} as any)
const DichVuRoute = DichVuRouteImport.update({
  id: '/dich-vu',
  path: '/dich-vu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dich-vu': typeof DichVuRoute
  '/du-an': typeof DuAnRoute
  '/ho-tro-sinh-vien': typeof HoTroSinhVienRoute
  '/lien-he': typeof LienHeRoute
  '/quy-trinh': typeof QuyTrinhRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/startup-mvp': typeof StartupMvpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dich-vu': typeof DichVuRoute
  '/du-an': typeof DuAnRoute
  '/ho-tro-sinh-vien': typeof HoTroSinhVienRoute
  '/lien-he': typeof LienHeRoute
  '/quy-trinh': typeof QuyTrinhRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/startup-mvp': typeof StartupMvpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dich-vu': typeof DichVuRoute
  '/du-an': typeof DuAnRoute
  '/ho-tro-sinh-vien': typeof HoTroSinhVienRoute
  '/lien-he': typeof LienHeRoute
  '/quy-trinh': typeof QuyTrinhRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/startup-mvp': typeof StartupMvpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dich-vu'
    | '/du-an'
    | '/ho-tro-sinh-vien'
    | '/lien-he'
    | '/quy-trinh'
    | '/sitemap.xml'
    | '/startup-mvp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dich-vu'
    | '/du-an'
    | '/ho-tro-sinh-vien'
    | '/lien-he'
    | '/quy-trinh'
    | '/sitemap.xml'
    | '/startup-mvp'
  id:
    | '__root__'
    | '/'
    | '/dich-vu'
    | '/du-an'
    | '/ho-tro-sinh-vien'
    | '/lien-he'
    | '/quy-trinh'
    | '/sitemap.xml'
    | '/startup-mvp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DichVuRoute: typeof DichVuRoute
  DuAnRoute: typeof DuAnRoute
  HoTroSinhVienRoute: typeof HoTroSinhVienRoute
  LienHeRoute: typeof LienHeRoute
  QuyTrinhRoute: typeof QuyTrinhRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartupMvpRoute: typeof StartupMvpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/startup-mvp': {
      id: '/startup-mvp'
      path: '/startup-mvp'
      fullPath: '/startup-mvp'
      preLoaderRoute: typeof StartupMvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quy-trinh': {
      id: '/quy-trinh'
      path: '/quy-trinh'
      fullPath: '/quy-trinh'
      preLoaderRoute: typeof QuyTrinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ho-tro-sinh-vien': {
      id: '/ho-tro-sinh-vien'
      path: '/ho-tro-sinh-vien'
      fullPath: '/ho-tro-sinh-vien'
      preLoaderRoute: typeof HoTroSinhVienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/du-an': {
      id: '/du-an'
      path: '/du-an'
      fullPath: '/du-an'
      preLoaderRoute: typeof DuAnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dich-vu': {
      id: '/dich-vu'
      path: '/dich-vu'
      fullPath: '/dich-vu'
      preLoaderRoute: typeof DichVuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DichVuRoute: DichVuRoute,
  DuAnRoute: DuAnRoute,
  HoTroSinhVienRoute: HoTroSinhVienRoute,
  LienHeRoute: LienHeRoute,
  QuyTrinhRoute: QuyTrinhRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartupMvpRoute: StartupMvpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
